#import "comm.typ": *

#show: comm.with(title: "Cover-letter", m: 0.5in)

Dear Hiring Team,

It is with great pleasure that I submit my candidacy for the *Job Title* with *Name of company*. I bring over three years of professional experience building backend systems, RAG pipelines, and production AI agents, along with a strong academic foundation as a Master of Science in Computer Science graduate from Pace University, NY.

Through my experience across two engineering roles, I have built and delivered production-grade backend and agentic systems that directly reflect *the technical depth this position demands*. As a Software Engineer at Sperse, I designed a multi-agent CRM orchestration system using LangChain, LangSmith, and FastAPI that routes requests to 40+ specialized sub-agents — with lazy-loaded tool context, prompt-injection defenses, and tenant-aware access control via JWT propagation through every agent. Alongside it, I engineered a production MCP server with FastMCP exposing 160+ LLM-callable tools over a multi-tenant .NET backend, built test-first with Pydantic validation and OpenTelemetry instrumentation. To keep these systems production-ready, I built OpenTelemetry trace-driven eval suites that replay real production conversations across prompts and model versions — scoring latency and tool-call accuracy and flagging unsafe behavior — and wired those eval suites into GitHub Actions CI/CD pipelines that gate every deploy. I also built LlamaIndex-powered RAG agents over our technical documentation using OpenAI embeddings in pgvector, and durable user-defined agentic workflows with React Flow and Inngest, complete with a fleet-management layer integrated with Slack and Teams for real-time observability across running agent swarms. Prior to Sperse, as a Software Engineer at Qualitest, I contributed to backbone infrastructure that users relied on daily. I designed a cloud-agnostic Storage Service using Python, PostgreSQL, and Redis that seamlessly handled file operations across AWS S3, Google Cloud Storage, and MinIO via expiring signed URLs — giving me direct, hands-on experience with cloud-native, multi-environment backend design. I also optimized PostgreSQL with window functions, materialized views, and indexing to cut query latency, exposing the results through interactive React.js visualizations for business stakeholders, and orchestrated long-running jobs with AWS Step Functions to eliminate Lambda timeouts and improve error recovery across 100K+ weekly executions — work that required *the kind of systems-level thinking and operational stability focus this role demands*. Together, these roles have prepared me to *contribute meaningfully to the team's core engineering responsibilities* and drive impact within an agile engineering team.

My academic research experience has given me a rigorous foundation in GPU-accelerated computing, model fine-tuning, and agentic system design — skills that translate directly into *the engineering discipline this team values*. As an AI Researcher at the Pace Artificial Intelligence Lab, I built an agentic optimization virtual lab that tunes CUDA kernels through evolutionary search paired with an ensemble of LLM judges, using LangGraph to orchestrate hypothesis generation and NVIDIA Nsight profiling to close the performance-feedback loop. I also fine-tuned Qwen3-8B with Unsloth and LoRA to internalize tool schemas directly into the model weights, reducing prompt tokens by roughly 70% at equal task accuracy. This work demanded careful experimental design, deep performance analysis, and the ability to reason about LLM behavior empirically rather than anecdotally — and it has shaped me into an engineer who builds with rigor and validates with evidence, both of which I would bring to *this team and its mission*.

I have always been passionate about *list 1-2 values or items from the company's mission statement* and envision myself contributing my talent to the furthering of *company goal*. I would love to discuss my interest in this position with your team and can be reached at #ph or #eml. Thank you for your time and consideration, I look forward to connecting!

#cv_ending()
